### ISSUE TITLE
[ERROR] lua/autorun/server/antifreeze.lua:1: Couldn't load module library!

### ISSUE THREAD

**Issue by FarikLoL** [storm37000/gmsv_antifreeze#1]
[ERROR] lua/autorun/server/antifreeze.lua:1: Couldn't load module library!
  1. require - [C]:-1
   2. unknown - lua/autorun/server/antifreeze.lua:1

**Comment by FarikLoL** [comment]
![image](https://user-images.githubusercontent.com/46515364/136282593-d74b8442-1dc7-4637-86df-dd653d352a35.png)

**Comment by storm37000** [comment]
I dont normally run windows for servers but It has worked in the past when I tested.  Make sure you have the latest c++ runtime installed (https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist).
