### ISSUE TITLE
help

### ISSUE THREAD

**Issue by FarikLoL** [storm37000/gmsv_antifreeze#4]
[ERROR] lua/autorun/server/antifreeze.lua:1: Couldn't load module library! (bin/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /root/steamcmd/garrysmod/garrysmod/lua/bin/gmsv_antifreeze_linux.dll))
  1. require - [C]:-1
   2. unknown - lua/autorun/server/antifreeze.lua:1

How to fix this?

**Comment by storm37000** [comment]
what Linux are you using?  I compile it on ubuntu 2004 for linux.  Anything less than that is out of support by the devs as of April 30, 2021.  It works properly on debian 10+ which is what I use.   (also you shoudn't run the server as root user).

**Comment by storm37000** [comment]
I can compile you a special version for old Ubuntu like 1804, but it might not work properly on modern OS.

**Comment by FarikLoL** [comment]
i'm using ubuntu 20.04 and yes i ran as root user (now too)
I fixed it by copy it all files from /usr/lib/x86_64-linux-gnu/ to the server_directory/bin

**Comment by storm37000** [comment]
that shouldnt be needed unless your system path is broken.  Also you should make symlinks (ln -s) instead of copying so that it all updates together whenever those libraries get an update.
